language: node_js
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - node

before_install:
  - export CXX="g++-4.9" CC="gcc-4.9"

script:
  - npm run standard
  - npm run test:node
  - npm run test:native

git:
  depth: 10

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
