language: node_js
sudo: required
dist: trusty
os:
  - linux
  - osx
node_js:
  - "7.0"
  - "6.0"
  - "4.0"

env:
  - CC=clang CXX=clang++ npm_config_clang=1

notifications:
  email: false

git:
  depth: 10

branches:
  only:
    - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -yq xvfb gnome-keyring libsecret-1-dev python-gnomekeyring; fi

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      dbus-launch /usr/bin/python -c \
        "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run ./script/cibuild; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm test; fi
