version: "{build}"

platform: x64

branches:
  only:
    - master

clone_depth: 10

skip_tags: true

install:
  - ps: Install-Product node 6
  - npm install

build_script:
  - npm test

test: off
deploy: off
