[package]
name = "xray_node"
version = "0.1.0"
authors = ["Nathan Sobo <nathan@github.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
xray_core = {path = "../xray_core"}
napi = {path = "../napi"}
